#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { llmContract } from "./index.mjs";

const packageRoot = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(packageRoot, "..");
const checkOnly = process.argv.includes("--check");
const plainContract = JSON.parse(JSON.stringify(llmContract));
const sourceHash = createHash("sha256")
  .update(JSON.stringify(plainContract))
  .digest("hex");
const contract = { sourceHash, ...plainContract };
const prettyContract = JSON.stringify(contract, null, 2);

const generatedModule = `// Generated by llm/generate.mjs from llm/. DO NOT EDIT.\n`
  + `// Canonical contract SHA-256: ${sourceHash}\n`
  + `const deepFreeze = (value) => {\n`
  + `  if (value && typeof value === "object" && !Object.isFrozen(value)) {\n`
  + `    Object.freeze(value);\n`
  + `    Object.values(value).forEach(deepFreeze);\n`
  + `  }\n`
  + `  return value;\n`
  + `};\n`
  + `export const LLM_CONTRACT = deepFreeze(${prettyContract});\n`
  + `export const DETECT_PROMPT = LLM_CONTRACT.prompts.detection.base;\n`
  + `export const DETECT_PROMPT_ROLE = LLM_CONTRACT.prompts.detection.role;\n`
  + `export const DETECT_PROMPT_VERSION = LLM_CONTRACT.prompts.detection.version;\n`
  + `export const DETECT_SCHEMA_VERSION = LLM_CONTRACT.prompts.detection.schemaVersion;\n`
  + `export const DETECT_SCHEMA = LLM_CONTRACT.prompts.detection.schema;\n`
  + `export const TENDER_INSTRUCTIONS = LLM_CONTRACT.prompts.tender.instructions;\n`
  + `export const TENDER_PROMPT_ROLE = LLM_CONTRACT.prompts.tender.role;\n`
  + `export const TENDER_DATA_ROLE = LLM_CONTRACT.prompts.tender.dataRole;\n`
  + `export const TENDER_SCHEMA = LLM_CONTRACT.prompts.tender.schema;\n`
  + `export const MODEL_CONFIG = LLM_CONTRACT.config.models;\n`
  + `export const RUNTIME_CONFIG = LLM_CONTRACT.config.runtime;\n`
  + `export const IMAGING_CONFIG = LLM_CONTRACT.config.imaging;\n`
  + `export const TENDER_CONFIG = LLM_CONTRACT.config.tender;\n`;

const browserModule = `// Generated by llm/generate.mjs from llm/. DO NOT EDIT.\n`
  + `// Canonical contract SHA-256: ${sourceHash}\n`
  + `(() => {\n`
  + `  const deepFreeze = (value) => {\n`
  + `    if (value && typeof value === "object" && !Object.isFrozen(value)) {\n`
  + `      Object.freeze(value);\n`
  + `      Object.values(value).forEach(deepFreeze);\n`
  + `    }\n`
  + `    return value;\n`
  + `  };\n`
  + `  window.PotholeLlmContract = deepFreeze(${prettyContract});\n`
  + `})();\n`;

function kotlinString(value) {
  return JSON.stringify(String(value)).replaceAll("$", "\\$");
}

function kotlinStringList(values) {
  return `setOf(${values.map(kotlinString).join(", ")})`;
}

function kotlinStringMap(value) {
  return `mapOf(${Object.entries(value)
    .map(([key, item]) => `${kotlinString(key)} to ${kotlinString(item)}`)
    .join(", ")})`;
}

const detection = contract.prompts.detection;
const tender = contract.prompts.tender;
const models = contract.config.models;
const runtime = contract.config.runtime;
const imaging = contract.config.imaging;
const tenderSettings = contract.config.tender;
const detectionEnumStrings = (field) => detection.schema.properties[field].enum
  .filter((value) => typeof value === "string");
const kotlinModule = `// Generated by llm/generate.mjs from llm/. DO NOT EDIT.\n`
  + `// Canonical contract SHA-256: ${sourceHash}\n`
  + `package com.gauravsen.potholereporter.drivemode\n\n`
  + `object LlmContractGenerated {\n`
  + `    const val SOURCE_SHA256 = ${kotlinString(sourceHash)}\n`
  + `    const val RESPONSES_URL = ${kotlinString(runtime.responsesUrl)}\n`
  + `    const val STORE_RESPONSES = ${runtime.storeResponses}\n`
  + `    const val TEXT_VERBOSITY = ${kotlinString(runtime.textVerbosity)}\n`
  + `    const val STRICT_STRUCTURED_OUTPUTS = ${runtime.strictStructuredOutputs}\n`
  + `    const val PERSONAL_DETECTION_STREAM = ${runtime.personalDetectionStream}\n`
  + `    const val PERSONAL_OPENAI_TIMEOUT_MS = ${runtime.timeoutsMs.personalOpenAI}L\n`
  + `    const val SHARED_VISION_TIMEOUT_MS = ${runtime.timeoutsMs.sharedVisionClient}L\n\n`
  + `    const val DEFAULT_MODEL = ${kotlinString(models.defaultModel)}\n`
  + `    val ALLOWED_MODELS: Set<String> = ${kotlinStringList(models.allowedModels)}\n`
  + `    val REASONING_EFFORT_BY_MODEL: Map<String, String> = ${kotlinStringMap(models.reasoningEffortByModel)}\n`
  + `    const val DEFAULT_REASONING_EFFORT = ${kotlinString(models.defaultReasoningEffort)}\n`
  + `    const val DEFAULT_IMAGE_DETAIL = ${kotlinString(models.defaultImageDetail)}\n`
  + `    const val ORIGINAL_IMAGE_DETAIL = ${kotlinString(models.originalImageDetail)}\n`
  + `    val ALLOWED_IMAGE_DETAILS: Set<String> = ${kotlinStringList(models.allowedImageDetails)}\n`
  + `    val ORIGINAL_DETAIL_MODELS: Set<String> = ${kotlinStringList(models.originalDetailModels)}\n\n`
  + `    const val DEFAULT_LANGUAGE = ${kotlinString(models.defaultLanguage)}\n`
  + `    val ALLOWED_LANGUAGES: Set<String> = ${kotlinStringList(models.allowedLanguages)}\n\n`
  + `    const val MAX_DETECTION_IMAGES = ${imaging.maxDetectionImages}\n`
  + `    const val MANUAL_MAX_DIMENSION = ${imaging.manual.maxDimension}\n`
  + `    const val MANUAL_JPEG_QUALITY = ${Math.round(imaging.manual.jpegQuality * 100)}\n`
  + `    const val DRIVE_MAX_DIMENSION = ${imaging.drive.maxDimension}\n`
  + `    const val DRIVE_JPEG_QUALITY = ${Math.round(imaging.drive.jpegQuality * 100)}\n`
  + `    const val DRIVE_ADAPTIVE_BRIGHTNESS = ${imaging.drive.adaptiveBrightness}\n`
  + `    const val LUMINANCE_TARGET_SAMPLES = ${imaging.adaptiveLuminance.targetSamples}\n`
  + `    const val LUMINANCE_MEAN_THRESHOLD = ${imaging.adaptiveLuminance.meanThreshold}f\n`
  + `    const val LUMINANCE_DARK_PIXEL_THRESHOLD = ${imaging.adaptiveLuminance.darkPixelThreshold}f\n`
  + `    const val LUMINANCE_BRIGHT_PIXEL_THRESHOLD = ${imaging.adaptiveLuminance.brightPixelThreshold}f\n`
  + `    const val LUMINANCE_BRIGHT_FRACTION_THRESHOLD = ${imaging.adaptiveLuminance.brightFractionThreshold}f\n`
  + `    const val LUMINANCE_TARGET_MEAN = ${imaging.adaptiveLuminance.targetMean}f\n`
  + `    const val LUMINANCE_MEAN_FLOOR = ${imaging.adaptiveLuminance.meanFloor}f\n`
  + `    const val LUMINANCE_MINIMUM_LIFT = ${imaging.adaptiveLuminance.minimumLift}f\n`
  + `    const val LUMINANCE_MAXIMUM_LIFT = ${imaging.adaptiveLuminance.maximumLift}f\n`
  + `    const val LUMINANCE_CONTRAST = ${imaging.adaptiveLuminance.contrast}f\n\n`
  + `    const val DETECT_PROMPT = ${kotlinString(detection.base)}\n`
  + `    const val DETECT_PROMPT_ROLE = ${kotlinString(detection.role)}\n`
  + `    const val DETECT_PROMPT_VERSION = ${kotlinString(detection.version)}\n`
  + `    const val DETECT_SCHEMA_VERSION = ${detection.schemaVersion}\n`
  + `    const val DETECT_SCHEMA_NAME = ${kotlinString(detection.schemaName)}\n`
  + `    const val DETECT_SCHEMA = ${kotlinString(JSON.stringify(detection.schema))}\n`
  + `    val DETECT_REQUIRED_FIELDS: List<String> = ${kotlinStringList(detection.schema.required).replace("setOf(", "listOf(")}\n`
  + `    val DETECT_IMAGE_QUALITIES: Set<String> = ${kotlinStringList(detectionEnumStrings("image_quality"))}\n`
  + `    val DETECT_ASSESSMENTS: Set<String> = ${kotlinStringList(detectionEnumStrings("assessment"))}\n`
  + `    val DETECT_DAMAGE_TYPES: Set<String> = ${kotlinStringList(detectionEnumStrings("damage_type"))}\n`
  + `    val DETECT_SIZES: Set<String> = ${kotlinStringList(detectionEnumStrings("size"))}\n`
  + `    const val DETECT_CAPTURE_MANUAL = ${kotlinString(detection.captureLayouts.manual)}\n`
  + `    const val DETECT_CAPTURE_DRIVE = ${kotlinString(detection.captureLayouts.drive)}\n`
  + `    const val DETECT_LANGUAGE_KN = ${kotlinString(detection.languageSuffixes.kn)}\n`
  + `\n`
  + `    const val TENDER_INSTRUCTIONS = ${kotlinString(tender.instructions)}\n`
  + `    const val TENDER_PROMPT_ROLE = ${kotlinString(tender.role)}\n`
  + `    const val TENDER_DATA_ROLE = ${kotlinString(tender.dataRole)}\n`
  + `    const val TENDER_SCHEMA_NAME = ${kotlinString(tender.schemaName)}\n`
  + `    const val TENDER_SCHEMA = ${kotlinString(JSON.stringify(tender.schema))}\n`
  + `    const val TENDER_MODEL = ${kotlinString(tenderSettings.model)}\n`
  + `    const val TENDER_REASONING_EFFORT = ${kotlinString(tenderSettings.reasoningEffort)}\n`
  + `    const val TENDER_MINIMUM_CONFIDENCE = ${tenderSettings.minimumConfidence}\n`
  + `}\n`;

const targets = new Map([
  ["llm/generated/contract.json", `${prettyContract}\n`],
  ["llm/generated/contract.mjs", generatedModule],
  ["static/llm-contract.generated.js", browserModule],
  ["android-app/www/llm-contract.generated.js", browserModule],
  ["android-app/android/app/src/main/assets/public/llm-contract.generated.js", browserModule],
  ["android-app/android/app/src/main/java/com/gauravsen/potholereporter/drivemode/LlmContractGenerated.kt", kotlinModule],
]);

const stale = [];
for (const [relativePath, expected] of targets) {
  const path = resolve(repositoryRoot, relativePath);
  if (checkOnly) {
    const actual = await readFile(path, "utf8").catch(() => null);
    if (actual !== expected) stale.push(relativePath);
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, expected);
  }
}

if (stale.length) {
  console.error(`Stale generated LLM contract files:\n- ${stale.join("\n- ")}\nRun: node llm/generate.mjs`);
  process.exitCode = 1;
} else {
  console.log(`${checkOnly ? "Verified" : "Generated"} LLM contract ${sourceHash}`);
}
